### ISSUE TITLE
Basic install not working

### ISSUE THREAD

**Issue by cheshirecat78** [vpaeder/tplink_m7350_cpp#1]
Hi vpaeder,

I cloned, installed the dependencies and compiled.

In the end leaves me with an error:

```
~/tplink_m7350_cpp/build$ ./send_sms -a my_ip -p my_pass -n my_mobile_nr -m test

send_sms: /usr/include/rapidjson/document.h:1078: rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator = rapidjson::GenericMemberIterator<true, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]: Assertion `IsObject()' failed.
Aborted
```

Can you help me out?

**Comment by vpaeder** [comment]
Hi,
I guess that's an issue with the modem reply. My modem is V5 so it's probable that there're changes with newer versions (and maybe firmwares too, unfortunately I don't have it at hand to check on that).
I updated the code to include some kind of debug messages (use cmake option -DCMAKE_BUILD_TYPE=Debug to activate them). Maybe you can test with the updated code to confirm that.
Cheers
Vincent

**Comment by vpaeder** [comment]
I checked TP-Link firmware page. For the latest V5 firmware I see this comment:
`1. Optimized login mechanism`

So indeed the code won't work with newer firmwares for now.

**Comment by cheshirecat78** [comment]
Aight.

Thanks for the swift reply and research.

I might look into it sometimes :)

Cheers
